#REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
#Sub To Mr Nomi MC
#Do Not change The Author Name!!
#Created By @Mr Nomi MC

#Gold Mine Command
gold: "warp gold"


#Redstone Mine Command
redstone: "warp redstone"


#Lapis Mine Command
lapis: "warp lapis"


#Emerlad Mine Command
emerald: "warp emerald"


#Diamond Mine Command
diamond: "warp diamond"


#Obsidian Mine Command
obsidian: "warp obsidian"



#YOU CANT ADD MORE FOR NOW !!